### ISSUE TITLE
code confusing

### ISSUE THREAD

**Issue by 2014gaokao** [husthuaan/AAT#1]
what does (1+(1-p)) and selector mean in self.att_cost += (1+(1-p)).squeeze(1) and selector = (p < 1 - self.epsilon).data?

**Comment by husthuaan** [comment]
Hi @2014gaokao ,

Thanks for your interest and sorry for the delay.

Please refre to equation 11 in the paper:
L_t^a =  N(t) + \sum_{n=0}^{N(t)} (n+1)(1-p_{t,n})

Selector indicates the samples of a batch that haven't finished the attention process (determined by its confidence).

(1+(1-p)) is the attention time cost at the zero attention step. And selector = (p < 1 - self.epsilon) indicates which samples need to perform attention after the first LSTM layer.
